### PR TITLE
avoid overrideing another Shift class

### PR DESCRIPTION
**Pull request by flemse**
I had a problem with Tod overriding an existing class called shift.

This is my first attempt at contributing to something so please bare with me if something is off.

### CODE REVIEW

**Comment by flemse** [comment]
I will close this since it seems to fail in a production environment.

**Comment by jackc** [comment]
Sorry I didn't get back to you quicker. I saw it was failing CI, but didn't immediately see why.

I wish I had not aliased TimeOfDay and Shift to the top level namespace. Unfortunately, what's done is done, and changing it will be a breaking change.

However, there are enough important changes pending that I will probably bite the bullet and release a backwards incompatible version in the next few weeks with better namespacing.

**Comment by flemse** [comment]
Thanks for the reply. 

I tried to make the override only happen if the class was not defined already. That would fit my needs.
But that only worked in development i later discovered.

Since you plan on changing this i will not iterate further on this, if that is ok with you?

**Comment by jackc** [comment]
FYI, I've made these (and other) improvements on the branch v2. Assuming no problems occur I plan on releasing the Ruby gem in a week or two.

**Comment by flemse** [comment]
Looking good :+1:

**Pull request closed without merging**
