### PR TITLE
Add include_without_borers method.

### PR DESCRIPTION
**Pull request by FUT**
In fact it is rather useful because I monkeypatching the gem second time right now. What do you think?

### CODE REVIEW

**Comment by jackc** [comment]
I like the idea, but it makes me think that maybe the Shift class really needs some more structural changes. It seems to really point at the fact that Shift is (or should be) a range (or range-like object). Ideally, the inclusiveness or exclusiveness should be encoded into the Shift. Then instead of having separate methods for include? and include_without_borders? it would just be include?.

Unfortunately, that is a little tough to do without breaking backwards compatibility. Possibly, expanding the Shift constructor with an optional argument might do the trick.

Maybe something like this to use standard math notation for ranges:

```
Shift.new(TimeOfDay.new(9), TimeOfDay.new(17), '[)')
```

Or maybe if we only support exclusivity on the right side:


```
Shift.new(TimeOfDay.new(9), TimeOfDay.new(17), true)
```

**Comment by jackc** [comment]
I've decided to release v2 of Tod with some small breaking changes. v2 supports Shifts with exclusive ends, just like Ruby ranges. It doesn't support exclusivity on the left side, but I think that is pretty rare (Ruby ranges do not, and that is how I am implementing it).

Do you think this will meet your needs? Checkout the v2 branch if you get a chance and try it out. I'm planning on releasing it in the next week or so.

**Comment by FUT** [comment]
I like your idea with third argument like `'[)'`. Unfortunately the v2 will not suit me. I've monkey-patched the gem to make it work well for me. Sorry for that :)

**Comment by jackc** [comment]
Cool. I also released a final version of the v1 branch (1.5) that includes all the latest code, but without any breaking changes.

**Pull request closed without merging**
